### Write a Python program to print the NumPy version in your system.

In [1]:
import numpy as np    # Importing NumPy library
print(f"The NumPy version is : {np.__version__}")    # Getting the version

The NumPy version is : 1.18.5


### Write a Python program to reverse an array (first element becomes last).

In [2]:
import numpy as np 
array1 = np.array([1,2,3,4,5,6,7])    # 1D array
array2 = np.array([[1,2],[3,4],[5,6]])    # 2D array 

print(f"The array is : {array1}")
print(f"The reversed array is : {array1[::-1]}")    # Reversing using slicing
print(f"The array is : {array2}")
print(f"The reversed array using slicing is : {array2[::-1]}")
print(f"The reversed array using flip function is : {np.flip(array2)}")
print(f"The reversed array using flipud function is : {np.flipud(array2)}")

The array is : [1 2 3 4 5 6 7]
The reversed array is : [7 6 5 4 3 2 1]
The array is : [[1 2]
 [3 4]
 [5 6]]
The reversed array using slicing is : [[5 6]
 [3 4]
 [1 2]]
The reversed array using flip function is : [[6 5]
 [4 3]
 [2 1]]
The reversed array using flipud function is : [[5 6]
 [3 4]
 [1 2]]


### Write a Python program to convert a list and tuple into arrays.

In [3]:

import numpy as np 
list1 = [1,2,3,4,5]
list2 = [1,4,9,16,25]
tupple1 = (0,2,6,8,20)

array3 = np.array(list1)    # Creating 1D array
array4 = np.array(list2)
array5 = np.array(tupple1)
array6 = np.array((list1,list2,tupple1))    # Creating 2D array

print(array3)
print(array4)
print(array5)
print(array6)

[1 2 3 4 5]
[ 1  4  9 16 25]
[ 0  2  6  8 20]
[[ 1  2  3  4  5]
 [ 1  4  9 16 25]
 [ 0  2  6  8 20]]


### Write a Python program to find common values between two arrays.

In [4]:
import numpy as np

array7 = np.array([1,2,3,4,5,6,7])
array8 = np.array([(0,7),(1,2),(1,9),(9,5)])

out_array1 = np.intersect1d(array7, array8)
# intersect1d function first faltens the array to 1D and then compares for common values

print(f"The common elements between the 2 arrays are : {out_array1}")

The common elements between the 2 arrays are : [1 2 5 7]


### Write a Python program compare two arrays using numpy.

In [5]:
import numpy as np

array9 = np.array([1,8,0,5,2,0,2,3])
array10 = np.array([0,7,0,8,2,0,2,2])

# Comparinson operators
print(array9 == array10)
print(array9 <= array10)
print(array9 >= array10)
print(array9 != array10)

[False False  True False  True  True  True False]
[False False  True  True  True  True  True False]
[ True  True  True False  True  True  True  True]
[ True  True False  True False False False  True]


### Write a Python program to change the dimension of an array.

In [7]:
import numpy as np

array11 = np.array([1, 9, 0, 5, 2, 0, 2, 3])
array12 = np.array([[0, 7, 0, 8], [2, 0, 2, 2]])

print(f"The array in 1D - {array11}")

#Using the reshape module in NumPy 
print(f"The array in 2D - {np.reshape(array11, (2, 4))}")
print(f"The array in 3D - {np.reshape(array11, (2, 2, 2))}")

print(f"The array in 2D - {array12}")
print(f"The array in 1D - {np.reshape(array12, 8)}")
print(f"The array in 3D - {np.reshape(array11, (2, 2, 2))}")

The array in 1D - [1 9 0 5 2 0 2 3]
The array in 2D - [[1 9 0 5]
 [2 0 2 3]]
The array in 3D - [[[1 9]
  [0 5]]

 [[2 0]
  [2 3]]]
The array in 2D - [[0 7 0 8]
 [2 0 2 2]]
The array in 1D - [0 7 0 8 2 0 2 2]
The array in 3D - [[[1 9]
  [0 5]]

 [[2 0]
  [2 3]]]


### Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

In [15]:
import numpy as np

#Using the arange function to get arrays of multiples of 3 and 5
array_mul3 = np.arange(0, 101, 3)
array_mul5 = np.arange(0, 101, 5)

print(f"The sum of all the multiples of 3 or 5 below 100 is : {np.sum(array_mul3) + np.sum(array_mul5)}")

The sum of all the multiples of 3 or 5 below 100 is : 2733


### Write a Python program to convert a NumPy array into Python list structure. 

In [23]:
import numpy as np

array11 = np.array([1, 9, 0, 5, 2, 0, 2, 3])
array12 = np.array([[0, 7, 0, 8], [2, 0, 2, 2]])

#Using tolist() function
print(f"Array 1 - {array11}")
print(f"Coverted to list : {array11.tolist()}")

print(f"\nArray 2 - {array12}")
print(f"Coverted to list : {array12.tolist()}")

Array 1 - [1 9 0 5 2 0 2 3]
Coverted to list : [1, 9, 0, 5, 2, 0, 2, 3]

Array 2 - [[0 7 0 8]
 [2 0 2 2]]
Coverted to list : [[0, 7, 0, 8], [2, 0, 2, 2]]


### Write a Python program to how to add an extra column to a numpy array.

In [36]:
import numpy as np

array12 = np.array([[0, 7, 0, 8], [2, 0, 2, 2]])
array13 = np.array([[1,2],[3, 4]])
print(f"\nThe array is\n{array12}")

#Using covatenate function
array14 = np.concatenate((array12, array13), axis = 1)
print(f"Adding 2 columns to the array : \n{array14}")


The array is
[[0 7 0 8]
 [2 0 2 2]]
Adding 2 columns to the array : 
[[0 7 0 8 1 2]
 [2 0 2 2 3 4]]


### Write a Python program to check whether the numpy array is empty or not.

In [57]:
import numpy as np

def check_size(arr):
    if arr.size == 0:
        print(f"Array {arr} is empty - Using size method")
    
    else:
        print(f"Array {arr} is not empty - Using size method")
    
def check_shape(arr):
    if arr.shape == 0:
        print(f"Array {arr} is empty - Using shape method")
    
    else:
        print(f"Array {arr} is not empty - Using shape method")
    
def check_len(arr):
    if len(arr) == 0:
        print(f"Array {arr} is empty - Using array length method")
    
    else:
        print(f"Array {arr} is not empty - Using array length method")   

array15 = np.array([1, 4, 0, 6, 2, 0, 2, 3])
array16 = np.array([])

check_size(array15)
check_size(array16)
check_shape(array15)
check_shape(array16)
check_len(array15)
check_len(array16)

Array [1 4 0 6 2 0 2 3] is not empty - Using size method
Array [] is empty - Using size method
Array [1 4 0 6 2 0 2 3] is not empty - Using shape method
Array [] is not empty - Using shape method
Array [1 4 0 6 2 0 2 3] is not empty - Using array length method
Array [] is empty - Using array length method


### How to ignore all numpy warnings (not recommended)?

In [63]:
import numpy as np
np.seterr(all = 'ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

### How to swap two rows of an array?

In [77]:
import numpy as np

array17 = np.array([[1, 4, 0, 6], [2, 0, 2, 3],[2, 0, 4, 2]])

print(f"The array is : \n{array17}")

#Selecting submatrix in the mentioned order to swap rows
print(f"Swapped array : \n {array17[[2, 1, 0]]}")
print(f"Swapped again : \n {array17[[1, 2, 0]]}")

The array is : 
[[1 4 0 6]
 [2 0 2 3]
 [2 0 4 2]]
Swapped array : 
 [[2 0 4 2]
 [2 0 2 3]
 [1 4 0 6]]
Swapped again : 
 [[2 0 2 3]
 [2 0 4 2]
 [1 4 0 6]]


### Python program to create a random vector of size 10 and sort it.

In [31]:
import numpy as np

array18 = np.random.random(10)    # Using the random module
print("The random vector is : ",array18)

array18.sort()    # Using the sort function 
print("After sorting : ",array18)

# Using arange function to generate a random array sorted
array23 = np.arange(10)
print("Another random vector : ",array23)

The random vector is :  [0.78775233 0.79434339 0.47073086 0.60933369 0.41451371 0.9394828
 0.09115026 0.39514043 0.36924103 0.19082216]
After sorting :  [0.09115026 0.19082216 0.36924103 0.39514043 0.41451371 0.47073086
 0.60933369 0.78775233 0.79434339 0.9394828 ]
Another random vector :  [0 1 2 3 4 5 6 7 8 9]


### Write a Python program to check two random arrays are equal or not.

In [26]:
import numpy as np

# Using random module to generate a random array
array19 = np.random.randn(10)
array20 = np.random.randn(10)

print("The random arrays are : ")
print(array19)
print(array20)

# Sorting the arrays to make comparison proper
array19.sort()
array20.sort()

# Using array_equal function to compare the random arrays
if np.array_equal(array19 , array20):  
    print("Both the arrays are similar")
    
else:
    print("Both the arrays are different")

The random arrays are : 
[-1.18813273  0.44705566 -0.02355209  1.74121239 -0.90115595  0.97263876
  0.52541452 -0.22771345  0.19494911  0.16728387]
[ 0.70913556  0.58536281 -1.35767582 -2.48528832 -0.58365506  1.14955656
 -0.74578376 -1.59659483 -0.13055295  0.90570861]
Both the arrays are different


### Write a Python program to add, subtract, multiply, divide arguments element-wise.

In [43]:
def addition(arr_1, arr_2):
    print("After adding each element : ",arr_1 + arr_2, sep='\n')
    
def subtraction(arr_1, arr_2):
    print("After subtracting each element : ",arr_1 - arr_2, sep='\n')
    
def multiplication(arr_1, arr_2):
    print("After multiplying each element : ",arr_1 * arr_2, sep='\n')
    
def division(arr_1, arr_2):
    print("After deviding each element : ",arr_1 / arr_2, sep='\n')
    
import numpy as np

# Using arange and reshaping it to a 3x3 array
array21 = np.arange(9).reshape(3,3)
print("First array :", array21, sep='\n')

# Using arange and reshaping it to a 3x3 array
array22 = np.arange(9).reshape(3,3)
print("Second array :", array22, sep='\n')

# Using the arrays as arguments to call the functions for basic operations
addition(array21, array22)
subtraction(array21, array22)
multiplication(array21, array22)
division(array21, array22)

First array :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Second array :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After adding each element : 
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
After subtracting each element : 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
After multiplying each element : 
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
After deviding each element : 
[[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


<ipython-input-43-b17dcd937599>:11: RuntimeWarning: invalid value encountered in true_divide
  print("After deviding each element : ",arr_1 / arr_2, sep='\n')


### Write a Python program to get the dates of yesterday, today and tomorrow.

In [68]:
import numpy as np

today = np.datetime64('today')    # Using the datetime module of numpy
yesterday = today - 1    # Subtracting 1 to get yesterday's date
tomorrow = today + 1    # Adding  to get tomorrow's date

print("Today : ", today)
print("Yesterday : ", yesterday)
print("Tomorrow : ", tomorrow)

Today :  2023-07-01
Yesterday :  2023-06-30
Tomorrow :  2023-07-02
